{% set name = "microsoft-kiota-serialization-text" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_text-{{ version }}.tar.gz
  sha256: 2a01d7257973faa8862fb759f0e957cb0c59e0760c30082a3a6efaafd60add2a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - microsoft-kiota-abstractions
    - python-dateutil 2.9.0

test:
  imports:
    - kiota_serialization_text
  commands:
    # disable pip check temporarily because of https://github.com/conda-forge/python-dateutil-feedstock/issues/29
    #- pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/text
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
