{% set name = "microsoft-kiota-serialization-text" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_text-{{ version }}.tar.gz
  sha256: c3dd3f409b1c4f4963bd1e41d51b65f7e53e852130bb441d79b77dad88ee76ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.0
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - python-dateutil >=2.8.2

test:
  imports:
    - kiota_serialization_text
  commands:
    # disable pip check temporarily because of https://github.com/conda-forge/python-dateutil-feedstock/issues/29
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/text
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
