{% set name = "microsoft-kiota-serialization-text" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_text-{{ version }}.tar.gz
  sha256: 0989f262dcf7703dd16bfcd70b2bf82b1100212c4a23e4ed0ec578da3250fc0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - microsoft-kiota-abstractions
    - python-dateutil 2.9.0

test:
  imports:
    - kiota_serialization_text
  commands:
    # disable pip check temporarily because of https://github.com/conda-forge/python-dateutil-feedstock/issues/29
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/serialization/text
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
